"""users table

Revision ID: 9b0dd58827d4
Revises: ce910dda2be2
Create Date: 2022-12-17 09:25:51.234370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b0dd58827d4'
down_revision = 'ce910dda2be2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('smth')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('smth', sa.VARCHAR(length=1024), nullable=True))

    # ### end Alembic commands ###
